TraineeHelper.Web/Controllers/ExerciseController.cs
using System.Web.Http;

namespace TraineeHelper.Web.Controllers
{
    //[ApiAuthenticationFilter(true)]
    public class ExerciseController : ApiController
    {
        //private readonly ExerciseService exerciseService;
        //
        //public ExerciseController()
        //{
        //    exerciseService = new ExerciseService();
        //}
        //
        //// Get: /api/exercise/514b46581cbfe31ad86ec630
        //public HttpResponseMessage Get(string id)
        //{
        //   
        //    //DataContractJsonSerializer jsonSerializer = new DataContractJsonSerializer(typeof(HttpResponseMessage));
        //    //HttpResponse response = Request.CreateResponse
        //    var exercise = exerciseService.GetById(id);
        //    if (exercise != null)
        //        //string json = JsonConvert.SerializeObject
        //        //object objResponse = jsonSerializer.ReadObject(exercise);
        //        return Request.CreateResponse(HttpStatusCode.OK, exercise, "application/json");
        //    return Request.CreateErrorResponse(HttpStatusCode.NotFound, "Exercise not found for provided id");
        //}
        //
        //// POST: /api/Exercise/Create
        ///*public async Task<HttpResponseMessage> Post([FromBody] DataModel.ExerciseContex exercise)
        //{
        //    await exerciseService.Create(exercise);
        //    return Request.CreateResponse(HttpStatusCode.Created, exercise);              
        //}
        //*/
        //
        //
        //// POST: /api/Exercise/Delete/514b46581cbfe31ad86ec630
        ////[ApiAuthenticationFilter(false)]
        //public HttpResponseMessage Delete(string id)
        //{
        //    try
        //    {
        //        exerciseService.Delete(id);
        //        return Request.CreateResponse(HttpStatusCode.OK);
        //    }
        //    catch
        //    {
        //        return Request.CreateErrorResponse(HttpStatusCode.NotFound, "Exercise not found or delete failed");
        //    }
        //}
        //
        //// PUT: /api/Exercise/Update
        ///*public HttpResponseMessage Update([FromBody] DataModel.ExerciseContex exercise)
        //{
        //    try
        //    {
        //        exerciseService.Update(exercise);
        //        return Request.CreateResponse(HttpStatusCode.OK);
        //    }
        //    catch
        //    {
        //        return Request.CreateErrorResponse(HttpStatusCode.NotFound, "Exercise not found or wrong update format");
        //    }
        //}
        //*/

    }
}

TraineeHelper.Web/Controllers/TrainerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TraineeHelper.Logic;
using TraineeHelper.ViewModels;

namespace TraineeHelper.Web.Controllers
{
    public class TrainerController : Controller
    {
        TrainerManager trainerManager;

        public TrainerController()
        {
            trainerManager = new TrainerManager();
        }
        // GET: Trainer
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<ActionResult> ViewTrainer(string trainerId)
        {
            ViewBag.Title = "ViewTrainer";
            ExpertiseManager expertisesManager = new ExpertiseManager();
            
            var trainerProfile = await trainerManager.ViewTrainerProfile(trainerId);
            List<string> expertisesIDs = new List<string>();
            foreach(string s in trainerProfile.Expertise)
            {
                expertisesIDs.Add(s);
            }
            var expertises = await expertisesManager.FindExpertisesByIds(expertisesIDs);
            ConnectionManager connectionManager = new ConnectionManager();
            bool connectionExists = await connectionManager.CheckConnectionExistence(Request.Cookies["userId"].Value, trainerId);
            ViewBag.AllowFriendshipRequest = !connectionExists;
            TempData["ViewerRating"] = 0;
            for(int i = 0; i < trainerProfile.Expertise.Length; i++)
            {
                trainerProfile.Expertise[i] = expertises[i].ExpertiseName;
            }
                                                        
            return View(trainerProfile);
            //return View(new UserTrainerProfileDataContext { UserName = "xxx" });
        }

        public ActionResult CreateTrainingPlanView()
        {
            ViewBag.Title = "CreateTrainingPlanView";

            return View();
        }

        public ActionResult CreateExercisesView()
        {
            ViewBag.Title = "CreateExercisesView";

            ExerciseContext exercise = new ExerciseContext();
            return View(exercise);
        }

        public ActionResult CreateChallengesForTraineeView()
        {
            ViewBag.Title = "CreateAchievementsForTraineeView";

            ChallengeContext challenge = new ChallengeContext();

            return View(challenge);
        }
    }
}

TraineeHelper.Web/Views/Trainer/CreateChallengesForTraineeView.cshtml
@model TraineeHelper.ViewModels.ChallengeContext

@{ 
    List<SelectListItem> ChallengeTypes = new List<SelectListItem>();
    List<SelectListItem> RunningDistance = new List<SelectListItem>();
    List<SelectListItem> WeightToLift = new List<SelectListItem>();
    List<SelectListItem> PushupsRepeats = new List<SelectListItem>();
    List<SelectListItem> ChallengeTimer = new List<SelectListItem>();

    ChallengeTypes.Add(new SelectListItem
    {
        Text = "Run",
        Value = "1"
    });

    ChallengeTypes.Add(new SelectListItem
    {
        Text = "Lift",
        Value = "2"
    });

    ChallengeTypes.Add(new SelectListItem
    {
        Text = "Pushups",
        Value = "3"
    });

    /* Distance To Run */
    RunningDistance.Add(new SelectListItem
    {
        Text = "500",
        Value = "500"
    });

    RunningDistance.Add(new SelectListItem
    {
        Text = "1000",
        Value = "1000"
    });

    RunningDistance.Add(new SelectListItem
    {
        Text = "2000",
        Value = "2000"
    });

    RunningDistance.Add(new SelectListItem
    {
        Text = "3000",
        Value = "3000"
    });

    RunningDistance.Add(new SelectListItem
    {
        Text = "4000",
        Value = "4000"
    });


    /* Weight To Lift */
    WeightToLift.Add(new SelectListItem
    {
        Text = "5",
        Value = "5"
    });

    WeightToLift.Add(new SelectListItem
    {
        Text = "8",
        Value = "8"
    });

    WeightToLift.Add(new SelectListItem
    {
        Text = "10",
        Value = "10"
    });

    WeightToLift.Add(new SelectListItem
    {
        Text = "15",
        Value = "15"
    });

    WeightToLift.Add(new SelectListItem
    {
        Text = "20",
        Value = "20"
    });

    /*Number of Pushups repetitions */
    PushupsRepeats.Add(new SelectListItem
    {
        Text = "10",
        Value = "10"
    });

    PushupsRepeats.Add(new SelectListItem
    {
        Text = "20",
        Value = "20"
    });

    PushupsRepeats.Add(new SelectListItem
    {
        Text = "30",
        Value = "30"
    });

    PushupsRepeats.Add(new SelectListItem
    {
        Text = "40",
        Value = "40"
    });

    PushupsRepeats.Add(new SelectListItem
    {
        Text = "50",
        Value = "50"
    });

    /* Time limit options */
    ChallengeTimer.Add(new SelectListItem
    {
        Text = "5",
        Value = "5"
    });

    ChallengeTimer.Add(new SelectListItem
    {
        Text = "7",
        Value = "7"
    });

    ChallengeTimer.Add(new SelectListItem
    {
        Text = "8",
        Value = "8"
    });

    ChallengeTimer.Add(new SelectListItem
    {
        Text = "10",
        Value = "10"
    });

    ChallengeTimer.Add(new SelectListItem
    {
        Text = "15",
        Value = "15"
    });
}
@using (Html.BeginForm())
{
    <h2>Challenge Builder</h2>

    @Html.AntiForgeryToken()
    <div class="form-group">
    
        @Html.Label("Challenge Type:", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-12">
            <div onchange="showHideBoxes()">
                @Html.DropDownList("Challenge Types", ChallengeTypes, "Select Challenge Type")
            </div>
            <div id="dvWeightsId" style="display: none;">
                @Html.Label("Weights:")
                @Html.DropDownList("Weights", WeightToLift, "Select Weight")
                @Html.Label("Kg")
            </div>
            <div id="dvPushupsRepeatsId" style="display: none;">
                @Html.Label("Pushups number:")
                @Html.DropDownList("Pushups number", PushupsRepeats, "Select Number Of PushUps")
                @Html.Label("times")
            </div>
            <div id="dvRunningDistanceId" style="display: none;">
                @Html.Label("Distance:")
                @Html.DropDownList("Running Distance", RunningDistance, "Select Distance")
                @Html.Label("meters")
            </div>
            <div id="dvChallengeTimerId" style="display: none;">
                @Html.Label("Time target:")
                @Html.DropDownList("Time Target", ChallengeTimer, "Select Time")
                @Html.Label("minutes") 
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                <input type="button" value="Add Another" onclick="addAnotherChallenge()" class="btn btn-default" />
                <input type="button" value="Finish" onclick="sendChallenges()" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<script type="text/javascript">
    function showHideBoxes() {
        var chkOption = $('#Challenge_Types').val();
        var weights = $('#Weights').val();
        var runningDistance = $('#Running_Distance').val();
        var pushupsRepeats = $('#Pushups_number').val();
        var timeTarget = $('#Time_Target').val();
        var dvWeights = document.getElementById("dvWeightsId");
        var dvPushupsRepeats = document.getElementById("dvPushupsRepeatsId");
        var dvRunningDistance = document.getElementById("dvRunningDistanceId");
        var dvChallengeTimer = document.getElementById("dvChallengeTimerId");

        if (chkOption == "1") {
            dvWeights.style.display = "none";
            dvPushupsRepeats.style.display = "none";
            dvRunningDistance.style.display = "block";
            dvChallengeTimer.style.display = "block";
            $('#Weights').prop("selectedIndex", 0);
            $('#Pushups_number').prop("selectedIndex", 0);
        }

        else if (chkOption == "2") {
            dvWeights.style.display = "block";
            dvPushupsRepeats.style.display = "none";
            dvRunningDistance.style.display = "none";
            dvChallengeTimer.style.display = "none";
            $('#Running_Distance').prop("selectedIndex", 0);
            $('#Pushups_number').prop("selectedIndex", 0);
            $('#Time_Target').prop("selectedIndex", 0);
        }
        else if (chkOption == "3") {
            dvWeights.style.display = "none";
            dvPushupsRepeats.style.display = "block";
            dvRunningDistance.style.display = "none";
            dvChallengeTimer.style.display = "none";
            $('#Running_Distance').prop("selectedIndex", 0);
            $('#Time_Target').prop("selectedIndex", 0);
            $('#Weights').prop("selectedIndex", 0);
        }
        else {
            dvWeights.style.display = "none";
            dvPushupsRepeats.style.display = "none";
            dvRunningDistance.style.display = "none";
            dvChallengeTimer.style.display = "none";
            $('#Running_Distance').prop("selectedIndex", 0);
            $('#Time_target').prop("selectedIndex", 0);
            $('#Weights').prop("selectedIndex", 0);
            $('#Pushups_number').prop("selectedIndex", 0);
        }
    }
    window.app = {
        challenges: []
    };

</script>

TraineeHelper.Web/Views/Trainer/CreateExercisesView.cshtml
@model TraineeHelper.ViewModels.ExerciseContext

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ExerciseContext</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.HiddenFor(model => model.ExerciseId)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExerciseName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExerciseName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExerciseName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExerciseType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExerciseType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExerciseType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SetsNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SetsNum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SetsNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Repetitions, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Repetitions, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Repetitions, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MuscleName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MuscleName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MuscleName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Add another" onclick="addAnotherExercise()" class="btn btn-default" />
                <input type="button" value="Finish" onclick="createTrainingPlan()" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script>
    window.app = {
        exercises: []
    };

</script>

TraineeHelper.Web/Views/Trainer/CreateTrainingPlanView.cshtml
@model TraineeHelper.ViewModels.TrainingPlanContext

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TrainingPlanContext</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.HiddenFor(model => Model.TrainerId)          
            @Html.HiddenFor(Mode => Model.TraineeId)
        </div>
        <div class="form-group">
            @Html.Label("Plan name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PlanName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PlanName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => Model.Created)
            @Html.HiddenFor(model => Model.StartDate)
            @Html.HiddenFor(model => Model.EndDate)
            @Html.HiddenFor(model => Model.CompletionDate)
        </div>

        @using (Html.BeginForm("Create", "Exercise", FormMethod.Post))
        {          
            <div>
                @Html.LabelFor(model => model.Exercises)
                
            </div>
        }

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
                <input type="button" onclick="CreateExercisesView()" value="Continue" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Home");
</div>

TraineeHelper.Web/Views/Trainer/ViewTrainer.cshtml
@model TraineeHelper.ViewModels.UserTrainerProfileDataContext
@{
    ViewBag.Title = "ViewTrainer";
}


<h2>Trainer Form</h2>

<div id="profile-form">
    <h2>@Model.UserName</h2>
    <table border="1">
        <tr>
            <td>UserName</td>
            <td>@Model.UserName</td>
        </tr>
        <tr>
            <td>Name</td>
            <td>@Model.Name</td>
        </tr>
        <tr>
            <td>Type</td>
            <td>@Model.UserType</td>
        </tr>
        <tr>
            <td>Gender</td>
            <td>@Model.Gender</td>
        </tr>
        <tr>
            <td>Location</td>
            <td>@Model.Location.City, @Model.Location.Country</td>
        </tr>
        <tr>
            <td>Birthday</td>
            <td>@Model.Birthday</td>
        </tr>
        <tr>
            <td>Phone</td>
            <td>@Model.PhoneNumber</td>
        </tr>
        <tr>
            <td>Email</td>
            <td>@Model.Email</td>
        </tr>
        <tr>
            <td>Reputation</td>
            <td>@Model.Reputation</td>
        </tr>
        <tr>
            <td>Expertise</td>
            <td>@foreach (string s in Model.Expertise)
            {
                @s
            }
            </td>
        </tr>
        <tr>
            <td>Experience</td>
            <td>@Model.ExperienceYears</td>
        </tr>
        <tr>
            <td>Price</td>
            <td>@Model.Price</td>
        </tr>        
        <tr>
            <td>Activity</td>
            <td>@Model.IsActive</td>
        </tr>
    </table>
</div>

<br />
@if (ViewBag.AllowFriendshipRequest)
{
    <input type="button" id="requestbtn" onclick="requestConnection('@Model.UserId')" value="request friendship" />
}

<div id="rating" style="display: block;" >
    <br />
    <input type="button" id="ratingbtn" onclick="ShowRatingInterface()" value="Rate Me" />
</div>


<div id="ratingInterface" style="display: none;">
    @Html.Label("Rate:")
    @foreach(var option in Model.ReputationOptions)
    {
        @Html.RadioButtonFor(i => option, option);
    }
    <br />
    <div id="num"  style="padding-left: 42px">
        <p>1 2 3 4 5</p>
        <input type="submit" onclick="updateRating('@Model.UserId')" value="Submit" />
    </div>
</div>

<div id="backToSearch">
    <br/>
    <input type="button" id="backToSearchbtn" onclick="location.href = '/Search/index'; "value="Back to search"/>
</div>

<div id="backToConnections">
    <br />
    <input type="button" id="backToConnectionbtn" onclick="location.href = '/Profile/Connections'; " value="Back to connections" />
</div>



<script type="text/javascript">
    function ShowRatingInterface() {
        var dvRating = document.getElementById("ratingInterface");
        dvRating.style.display = "block"
    }
</script>