TraineeHelper.Web/Controllers/TraineeViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TraineeHelper.Logic;
using TraineeHelper.ViewModels;

namespace TraineeHelper.Web.Controllers
{
    public class TraineeViewController : Controller
    {
        private TraineeManager traineeManager;
        private UserManager userManager;

        public TraineeViewController()
        {
            traineeManager = new TraineeManager();
            userManager = new UserManager();
        }
        // GET: TraineeView
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<ActionResult> ViewTrainee(string traineeId)
        {
            ViewBag.Title = "ViewTrainee";
            ViewBag.AllowFriendshipRequest = false;
            var traineeProfile = await traineeManager.ViewTraineeProfile(traineeId);
            var viewerUserType = (await userManager.GetById(Request.Cookies["userId"].Value)).UserType;
            HttpCookie watchedUserCookie = new HttpCookie("watchedUserId");
            watchedUserCookie.Value = traineeProfile.UserId;
            Response.Cookies.Add(watchedUserCookie);
            //Request.Cookies["watchedUserId"].Value = traineeProfile.UserId;
            ConnectionManager connectionManager = new ConnectionManager();
            bool connectionExists = await connectionManager.CheckConnectionExistence(Request.Cookies["userId"].Value, traineeId);
            ViewBag.AllowFriendshipRequest = !connectionExists;
            
            //var connection = await connectionManager.FindConnectionById(Request.Cookies["userId"].Value);
            //if(connection.ConnectionType != Common.ConnectionType.Mentor)
            //{
            ViewBag.ViewerUserType = viewerUserType;
            if (connectionExists && viewerUserType == "Trainer")
            {
                ViewBag.AllowMentorOptions = false;
                var connectionStatus = await connectionManager.GetConnectionStatus(Request.Cookies["userId"].Value, traineeId);
                if (connectionStatus == Common.ConnectionStatus.ACCEPTED)
                    ViewBag.AllowMentorOptions = true;
            }
            else
            {
                ViewBag.AllowMentorOptions = false;
            }
                
            //}
            //else
            //{
            //    ViewBag.AllowMentorOptions = connectionExists;
            //}
            

            return View(traineeProfile);
        }


        public async Task<ActionResult> PersonalProfile()
        {
            //ViewBag.Title = "PersonaProfileView";
            string userId = Request.Cookies["userId"].Value;

            TraineeContext trainee = await traineeManager.GetById(userId);

            return View(trainee);
        }

        public async Task<ActionResult> ViewTraineeMedicalCondition(string traineeId)
        {
            ViewBag.Title = "ViewTraineeMedicalCondition";
            //string userId = Request.Cookies["userId"].Value;
            TraineeContext trainee = await traineeManager.GetById(traineeId);
            ViewBag.traineeId = traineeId;

            return View(trainee.MedicalCondition);
        }

        public async Task<ActionResult> ViewTraineeTrainingPlans(string traineeId)
        {
            ViewBag.Title = "ViewTraineeTrainingPlans";
            TrainingPlanManager tpManager = new TrainingPlanManager();
            var trainingPlans = await tpManager.FindUserTrainingPlans(traineeId);
            return View(trainingPlans);
        }
        
        public async Task<ActionResult> ViewTrainingPlanDetails(string TrainingPlanId)
        {
            ViewBag.Title = "ViewTrainingPlanDetails";
            TrainingPlanManager tpManager = new TrainingPlanManager();
            var trainingPlan = await tpManager.FindTrainingPlanById(TrainingPlanId);

            return View(trainingPlan.Exercises);
        }
    }
}

TraineeHelper.Web/Views/TraineeView/PersonalTraineeProfile.cshtml
@model TraineeHelper.ViewModels.TraineeContext

@{
    ViewBag.Title = "PersonalTraineeProfile";
}

<h2>Personal Trainee Profile</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@Model.UserName</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.UserType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneVisibility, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.PhoneVisibility)
                    @Html.ValidationMessageFor(model => model.PhoneVisibility, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserVisibility, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.UserVisibility)
                    @Html.ValidationMessageFor(model => model.UserVisibility, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Modified, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Modified, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Modified, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Birthday, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Birthday, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TraineeHelper.Web/Views/TraineeView/ViewTrainee.cshtml
@model TraineeHelper.ViewModels.UserTraineeProfileDataContext
@{
    ViewBag.Title = "ViewTrainee";
}

<h2>Trainee Form</h2>

<div id="profile-form">
    <h2>@Model.UserName</h2>
    <table border="1">
        <tr>
            <td>UserName</td>
            <td>@Model.UserName</td>
        </tr>
        <tr>
            <td>Name</td>
            <td>@Model.Name</td>
        </tr>
        <tr>
            <td>Type</td>
            <td>@Model.UserType</td>
        </tr>
        <tr>
            <td>Gender</td>
            <td>@Model.Gender</td>
        </tr>
        <tr>
            <td>Location</td>
            <td>@Model.Location.City, @Model.Location.Country</td>
        </tr>
        <tr>
            <td>Email</td>
            <td>@Model.Email</td>
        </tr>
        <tr>
            <td>Favorite Exercise</td>
            <td>@Model.FavouriteExercise.ExerciseName</td>
        </tr>
        <tr>
            <td>Phone Number</td>
            <td>@Model.PhoneNumber</td>
        </tr>
        <tr>
            <td>Birthday</td>
            <td>@Model.Birthday</td>
        </tr>
        <tr>
            <td>Activity</td>
            <td>@Model.IsActive</td>
        </tr>

     </table>
</div>

<div>
    <br/>
    <input type="button" onclick="location.href = '/Search/index'" value="Go Back" />
    <br/>
    @if (ViewBag.AllowFriendshipRequest && @Model.UserType == "Trainee" && ViewBag.ViewerUserType == "Trainer") { 
       <input type="button" id="requestbtn" onclick="requestConnection('@Model.UserId', 'Mentor')" value="request mentorship" />
    }
    @if (ViewBag.AllowFriendshipRequest && @Model.UserType == "Trainer" && ViewBag.ViewerUserType == "Trainee")
    {
        <input type="button" id="requestbtn" onclick="requestConnection('@Model.UserId','Mentor')" value="request friendship" />
    }
    @if (ViewBag.AllowFriendshipRequest && Model.UserType != "Trainer" && ViewBag.ViewerUserType == "Trainee")
    {
        <input type="button" id="requestbtn" onclick="requestConnection('@Model.UserId', 'Friendship')" value="request mentorship" />
    }
    @if (ViewBag.AllowFriendshipRequest && @Model.UserType != "Trainee" && ViewBag.ViewerUserType == "Trainer")
    {
        <input type="button" id="requestbtn" onclick="requestConnection('@Model.UserId', 'Friendship')" value="request mentorship" />
    }
    @if (ViewBag.AllowMentorOptions)
    {
        <input type="button" id="medicalcondition" onclick="requestMedicalCondition('@Model.UserId')" value="Medical Condition" />
        <input type="button" id="trainingPlan" onclick="location.href = '/Trainer/CreateTrainingPlanView'" value="Send Training Plan" />
        <input type="button" id="challengebtnId" onclick="location.href = '/Trainer/CreateChallengesForTraineeView'" value="Send Challenges" />
    }
</div>

TraineeHelper.Web/Views/TraineeView/ViewTraineeMedicalCondition.cshtml
@model TraineeHelper.ViewModels.MedicalConditionContext

<div>
    <h4>MedicalConditionContext</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MuscleMass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MuscleMass)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FatPercent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FatPercent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Height)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Height)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

    </dl>
</div>
<p>
    
    @Html.ActionLink("Back to List", "ViewTrainee", "TraineeView", new {traineeId = ViewBag.traineeId }, null)
</p>

TraineeHelper.Web/Views/TraineeView/ViewTraineeTrainingPlans.cshtml
@model IEnumerable<TraineeHelper.ViewModels.TrainingPlanContext>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TrainerId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TraineeId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PlanName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Created)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CompletionDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TrainerId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TraineeId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PlanName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Created)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CompletionDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

TraineeHelper.Web/Views/TraineeView/ViewTrainingPlanDetails.cshtml
@model IEnumerable<TraineeHelper.ViewModels.ExerciseContext>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ExerciseId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ExerciseName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ExerciseType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SetsNum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Repetitions)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Note)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MuscleName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ExerciseId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ExerciseName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ExerciseType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SetsNum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Repetitions)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Note)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MuscleName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>